#!/bin/bash

if [ -z $1 ]
then
    echo "Usage: $0 file [out-dir]"
    exit
fi

OUT_DIR=.

if [ ! -z $2 ]
then
    OUT_DIR=$2
fi

if ! [ -f $1 ]
then
    echo "File '$1' does not exist"
    exit
fi

vim "$1" -c "syntax off | hardcopy > /tmp/printing.ps | q"

OUT_NAME="$(basename "$1" | sed 's/\(.*\)\..*/\1/')_$(date +"%y%m%d_%I%M%S").pdf"

echo "TESTE $1 -> $2$OUT_DIR"

ps2pdf /tmp/printing.ps "$OUT_DIR/$OUT_NAME"
rm /tmp/printing.ps

if ! [ -z $3 ]
then
    rm $1
fi
