#!/bin/bash

MIN=60
MAX=180
MAX_TIME=20000
DIR="$HOME/www/prints"
TIME=0

while [ $TIME -lt $MAX_TIME ]
do
	SECONDS_TO_PRINT=$(($MIN + $RANDOM % ($MAX - $MIN + 1)))
	TIME=$(($TIME + $SECONDS_TO_PRINT))
	sleep $SECONDS_TO_PRINT
	if [ "$(ls -A $DIR/.pending)" ]
	then
		mv $DIR/.pending/* $DIR
	fi
done

./print-end