#!/bin/bash

if [ -f pid.txt ]
then
	echo "Printer already running"
	exit
fi

echo "Starting printer loop"
./print-loop & disown

echo $! > pid.txt

echo "To print a file, use the print-file command: ./print-file file.txt"
echo "Prints will be available at https://linux.ime.usp.br/~gustavodmc/prints/"

